In [49]:
import pandas as pd
import math

In [50]:
df_resultat_20point = pd.read_csv('new_algo_resultat_pour20points.csv', encoding='latin')

In [51]:
df_resultat_20point["temps_mis_execution"] = df_resultat_20point["temps_mis_execution"] / 1e9
df_resultat_20point.columns =['nb_chemin', 'nombre_de_generation', 'distance', 'temps_mis_execution_en_second']

In [52]:
min = df_resultat_20point["temps_mis_execution_en_second"].sum()/60
print("Temps total:",math.floor(min),"min",math.floor((min % 1) * 60),"sec")

Temps total: 14 min 1 sec

In [53]:
df_resultat_20point_moyenne = df_resultat_20point.groupby(["nb_chemin","nombre_de_generation"])[["distance","temps_mis_execution_en_second"]].mean().reset_index()

In [54]:

df_resultat_20point_moyenne.sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
27,210,1000,8731.022568,2.536840
31,300,1000,8825.431049,4.085028
23,150,1000,8854.448693,1.891883
30,300,500,8868.768423,1.776245
19,120,1000,8978.709868,1.481049
26,210,500,9015.404257,1.355167
22,150,500,9052.513949,0.994388
15,90,1000,9073.972655,1.179187
18,120,500,9125.618506,0.764080
29,300,120,9243.553957,0.439138
14,90,500,9298.222299,0.563871
25,210,120,9320.030831,0.311908
28,300,60,9483.447930,0.223753
11,60,1000,9485.534462,0.790638
21,150,120,9605.056063,0.226985
17,120,120,9639.084528,0.200457
10,60,500,9663.873643,0.395223
24,210,60,9711.211578,0.160136
13,90,120,10005.016320,0.147150
20,150,60,10137.540320,0.116793
16,120,60,10171.509401,0.101811
9,60,120,10484.309910,0.093846
12,90,60,10529.195796,0.073286
7,30,1000,10762.467866,0.367569
6,30,500,11278.815347,0.187525
8,60,60,11424.717540,0.046328
3,21,1000,11775.725778,0.266685
2,21,500,11928.660049,0.136841
5,30,120,12043.442900,0.044016
4,30,60,12643.017463,0.021508
1,21,120,12815.203313,0.034896
0,21,60,13482.699421,0.018544

In [55]:
mask_gen_60 = df_resultat_20point["nombre_de_generation"] == 60
mask_gen_120 = df_resultat_20point["nombre_de_generation"] == 120
mask_gen_500 = df_resultat_20point["nombre_de_generation"] == 500
mask_gen_1000 = df_resultat_20point["nombre_de_generation"] == 1000
mask_gen_10000 = df_resultat_20point["nombre_de_generation"] == 10000
mask_gen_20000 = df_resultat_20point["nombre_de_generation"] == 20000

In [56]:
df_resultat_20point[mask_gen_60].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
1146,300,60,8669.319450,0.218857
814,150,60,8673.748220,0.111397
1121,300,60,8790.101568,0.228104
998,210,60,8870.623241,0.155202
807,150,60,8893.116022,0.115730
...,...,...,...,...
38,21,60,14236.534763,0.017993
12,21,60,14243.196954,0.019948
23,21,60,14270.315210,0.016185
29,21,60,14273.685481,0.017703
39,21,60,14728.965491,0.016648

In [57]:
df_resultat_20point[mask_gen_120].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
1019,210,120,8750.788028,0.311025
1169,300,120,8810.796773,0.435957
1199,300,120,8823.954572,0.430210
1183,300,120,8852.792186,0.428423
694,120,120,8882.454185,0.196532
...,...,...,...,...
69,21,120,13559.076867,0.032908
64,21,120,13708.766196,0.045728
220,30,120,13724.742990,0.041327
238,30,120,13746.245912,0.043042
66,21,120,14049.857786,0.032128

In [58]:
df_resultat_20point[mask_gen_500].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
1204,300,500,8451.993929,1.776691
1222,300,500,8581.077619,1.740737
881,150,500,8602.011712,1.009166
1210,300,500,8602.761675,1.762639
732,120,500,8629.056532,0.819439
...,...,...,...,...
116,21,500,12743.239827,0.152312
82,21,500,12872.722583,0.141949
95,21,500,12880.619658,0.140162
108,21,500,13019.183199,0.127850
102,21,500,13131.988125,0.141869

In [59]:
df_resultat_20point[mask_gen_1000].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
1111,210,1000,8246.621079,2.466019
1094,210,1000,8384.512441,2.771184
930,150,1000,8439.649362,1.886722
1267,300,1000,8448.672677,3.644559
940,150,1000,8466.954445,1.902978
...,...,...,...,...
148,21,1000,12359.380747,0.259638
143,21,1000,12446.560242,0.266466
158,21,1000,12552.507481,0.251949
138,21,1000,12645.267746,0.251369
131,21,1000,12668.344357,0.274946

In [60]:
df_resultat_20point.describe()

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
count,1280.000000,1280.000000,1280.000000,1280.000000
mean,122.625000,420.000000,10170.569584,0.657274
std,89.299857,375.113222,1391.290582,0.885009
min,21.000000,60.000000,8246.621079,0.015942
25%,52.500000,105.000000,9110.430634,0.112357
50%,105.000000,310.000000,9647.584480,0.249478
75%,165.000000,625.000000,11012.014603,0.896158
max,300.000000,1000.000000,14728.965491,4.893736