In [1]:
import pandas as pd
import math

In [2]:
df_resultat_20point = pd.read_csv('new_resultat_pour20points.csv', encoding='latin')

In [3]:
df_resultat_20point["temps_mis_execution"] = df_resultat_20point["temps_mis_execution"] / 1e9
df_resultat_20point.columns =['nb_chemin', 'nombre_de_generation', 'distance', 'temps_mis_execution_en_second']

In [4]:
min = df_resultat_20point["temps_mis_execution_en_second"].sum()/60
print("Temps total:",math.floor(min),"min",math.floor((min % 1) * 60),"sec")

Temps total: 13 min 41 sec

In [5]:
df_resultat_20point_moyenne = df_resultat_20point.groupby(["nb_chemin","nombre_de_generation"])[["distance","temps_mis_execution_en_second"]].mean().reset_index()

In [6]:

df_resultat_20point_moyenne.sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
31,300,1000,9747.242186,3.505963
30,300,500,9945.334004,1.868200
27,210,1000,9991.688323,2.653547
23,150,1000,10044.841297,1.898565
26,210,500,10096.347821,1.332448
19,120,1000,10136.760652,1.505704
22,150,500,10290.917526,0.938659
18,120,500,10332.217218,0.752443
15,90,1000,10380.500802,1.144904
14,90,500,10503.879147,0.576153
11,60,1000,10616.671868,0.752461
29,300,120,10634.880892,0.468262
10,60,500,10644.667224,0.362598
25,210,120,10742.836079,0.318993
28,300,60,11020.265492,0.235453
21,150,120,11126.605996,0.227995
13,90,120,11129.344032,0.149022
7,30,1000,11149.480764,0.377153
24,210,60,11150.736358,0.163220
17,120,120,11180.352992,0.184435
9,60,120,11297.712415,0.095244
6,30,500,11386.011185,0.181995
20,150,60,11405.680900,0.113439
12,90,60,11420.153275,0.069397
3,21,1000,11545.429653,0.267357
16,120,60,11569.739658,0.092033
2,21,500,11835.782514,0.142624
8,60,60,12122.503155,0.049853
5,30,120,12183.297806,0.042373
4,30,60,12656.076935,0.020998
1,21,120,12721.362637,0.034428
0,21,60,13262.026937,0.018525

In [7]:
mask_gen_60 = df_resultat_20point["nombre_de_generation"] == 60
mask_gen_120 = df_resultat_20point["nombre_de_generation"] == 120
mask_gen_500 = df_resultat_20point["nombre_de_generation"] == 500
mask_gen_1000 = df_resultat_20point["nombre_de_generation"] == 1000
mask_gen_10000 = df_resultat_20point["nombre_de_generation"] == 10000
mask_gen_20000 = df_resultat_20point["nombre_de_generation"] == 20000

In [8]:
df_resultat_20point[mask_gen_60].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
667,120,60,9761.775111,0.092535
501,90,60,9838.658007,0.068607
962,210,60,9966.162413,0.169140
969,210,60,9981.636969,0.167617
1148,300,60,9998.582388,0.234715
...,...,...,...,...
33,21,60,14006.107743,0.017242
169,30,60,14016.196537,0.020464
30,21,60,14017.576673,0.016774
23,21,60,14230.071756,0.016242
17,21,60,14787.244746,0.016719

In [9]:
df_resultat_20point[mask_gen_120].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
845,150,120,9314.374006,0.222437
1179,300,120,9552.161102,0.457798
398,60,120,9624.123259,0.091937
1194,300,120,9711.659392,0.454264
1021,210,120,9821.474109,0.303732
...,...,...,...,...
234,30,120,13338.223236,0.046076
59,21,120,13369.404722,0.034956
57,21,120,13496.238576,0.036961
66,21,120,13514.874619,0.037823
74,21,120,13556.518311,0.031772

In [10]:
df_resultat_20point[mask_gen_500].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
1075,210,500,9189.160394,1.391827
431,60,500,9202.646011,0.367373
749,120,500,9281.803914,0.744459
1202,300,500,9345.307736,1.875067
1217,300,500,9375.162388,1.882896
...,...,...,...,...
96,21,500,12493.163513,0.150021
107,21,500,12633.450754,0.156500
91,21,500,12650.983117,0.158067
103,21,500,12686.982716,0.140417
118,21,500,12958.699926,0.131915

In [11]:
df_resultat_20point[mask_gen_1000].sort_values("distance")

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
1278,300,1000,9156.931615,3.460643
933,150,1000,9162.330053,1.915566
1270,300,1000,9195.878828,3.701538
1089,210,1000,9230.699766,2.844725
796,120,1000,9240.273117,1.471758
...,...,...,...,...
124,21,1000,12104.774632,0.266277
155,21,1000,12112.687146,0.258038
125,21,1000,12183.990242,0.273330
153,21,1000,12224.476308,0.262154
144,21,1000,12297.185522,0.266947

In [12]:
df_resultat_20point.describe()

,nb_chemin,nombre_de_generation,distance,temps_mis_execution_en_second
count,1280.000000,1280.000000,1280.000000,1280.000000
mean,122.625000,420.000000,11070.979617,0.642014
std,89.299857,375.113222,986.549952,0.828096
min,21.000000,60.000000,9156.931615,0.015462
25%,52.500000,105.000000,10310.531439,0.109866
50%,105.000000,310.000000,10953.588484,0.254429
75%,165.000000,625.000000,11684.771579,0.870634
max,300.000000,1000.000000,14787.244746,4.015483